/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_bucles_5;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        
        int cAtras = 21;
        
    while (cAtras >=1){
	System.out.println(cAtras - 1); cAtras--;
        }
    }
}
