/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_var_4;

public class App {

    public static void main(String[] args) {

        
        String Nombre = "Juanje" ;
        String Direccion = "C/Orson Welles" ;
        int Telefono = 625594285 ;

        System.out.println("Tu nombre es " + Nombre);
        System.out.println("Tu direccion es " + Direccion);
        System.out.println("Tu telefono es " + Telefono);
         
}
}