/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_bucles_6;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner teclado = new Scanner (System.in);
        int i = 20;
                do{
                    System.out.println(i);
                    i--;
                }while(i != 0);

    }
}

