/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_if_3;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        
        Scanner teclado = new Scanner(System.in);

        int sueldo;
        
        System.out.print("Por favor introduzca horas trabajadas: ");
       int horas = teclado.nextInt();
        
        
        if (horas <= 40) {
            sueldo = 15 * horas;
        } else {
            sueldo = (40 * 15) + ((horas - 40) * 20);
        }
                
        System.out.println("El sueldo es de " + sueldo + " euros");
    }
}
