/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejercicio_if_4;

import java.util.Scanner;

public class App {
public static void main(String[] args) {
        
        Scanner teclado = new Scanner(System.in);
        
        System.out.println("Escriba la nota de Geografía (0-10)");
        float nota1 = teclado.nextFloat();
        
        System.out.println("Escriba la nota de Matemáticas (0-10)");
        float nota2 = teclado.nextFloat();
        
        System.out.println("Escriba la nota de Lengua(0-10)");
        float nota3 = teclado.nextFloat();
        
        float nmedia = (nota1 + nota2 + nota3) / 3;
        

       if (nmedia < 5) {
        System.out.print("Insuficiente");
    }           
       else if (nmedia >= 5 && nmedia < 6){
        System.out.print("Suficiente, ");
    }   
       else if (nmedia >= 6 && nmedia < 7){
        System.out.print("Bien, ");
    }  
       else if (nmedia >= 7 && nmedia < 8.5){
        System.out.print("Notable, ");
    }  
       else if (nmedia >= 8.5 && nmedia <= 10){
        System.out.print("Sobresaliente, ");
    }       
    System.out.println("La nota media es " + nmedia);
    }   
}
