/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_diabetes;

import java.util.Scanner;

public class App { //todo esto es una clase

    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in); //teclado = objeto
        int select;
        int nivel;
        System.out.println("Ingrese el nivel de azúcar en sangre del sujeto:");
        nivel = teclado.nextInt();

        if (nivel < 70) {
                System.out.println("Hipoglucemia, ¿está consciente el paciente? ");
        
                System.out.println("1. Si");
                //mensaje Objeto-> Sistema. Objeto-> Fuera. Método(para objeto)/Mensaje-> imprime  //parametro->("esto")
                System.out.println("2. No");

                select = teclado.nextInt();

                if (select == 1) {
                    System.out.println("Dar líquidos azucarados de absorción.");
                } else if (select == 2) {
                    System.out.println("No dar alimento o bebida por la boca.");
                }

            
            
            
        }else if (nivel >= 70 && nivel < 180) {
            System.out.println("El paciente no tiene diabetes.");
        }else  if (nivel >= 180) {
            System.out.println("El paciente tiene Hiperglucemia, acudir al hospital.");
        }
    }
}
