/*
 * This Java source file was generated by the Gradle 'init' task.
 */
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_var_5;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        //(EJERCICIO 5)
        //String nombre, direccion, telefono; (también se puede declarar así)
        Scanner teclado = new Scanner(System.in);
        
        int Telefono;
        String Nombre;
        String Direccion;
        
        System.out.println("¿Cuál es tu nombre?");
        Nombre = teclado.next();
        System.out.println("¿Cuál es tu dirección?");
        Direccion = teclado.next();
        System.out.println("¿Cuál es tu número?");
        Telefono = teclado.nextInt();

        System.out.println("Tu nombre es " + Nombre);
        System.out.println("Tu direccion es " + Direccion);
        System.out.println("Tu telefono es " + Telefono);

        
        /*(EJERCICIO 3)
        String NombreCompleto = "Juan Jesús Martín Costa" ;
        System.out.println("Tu nombre es " + NombreCompleto);
         */
    }

}
