/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_if_5;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        
        Scanner teclado = new Scanner(System.in);
        
        System.out.println("Añada el primer número");
        int num1 = teclado.nextInt();
        
        System.out.println("Añada el segundo número");
        int num2 = teclado.nextInt();
        
        System.out.println("Añada el tercer número");
        int num3 = teclado.nextInt();
        
       if(num1 >= num2 && num2 >= num3) {
       System.out.println(""+ num1 + " " + num2 + " " + num3);
    }
       else if (num1 >= num3 && num3 >= num2){
       System.out.print(""+ num1 + " " + num3 + " " + num2);
    }
       else if(num2 >= num1 && num1 >= num3) {
       System.out.print(""+ num2 + " " + num1 + " " + num3);
    }
       else if(num2 >= num3 && num3 >= num1) {
       System.out.print(""+ num2 + " " + num3 + " " + num1);
    }
       else if(num3 >= num2 && num2 >= num1) {
       System.out.print(""+ num3 + " " + num2 + " " + num1);
    }
       else if(num3 >= num1 && num1 >= num2) {
       System.out.print(""+ num3 + " " + num1 + " " + num2);
    }
}
}
