/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_var_6;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner teclado = new Scanner(System.in);
        float precio;
        float IVA;
        float precioFinal;
        
        System.out.println("¿Cuál es su precio?");
        precio = teclado.nextInt();
        System.out.println("");
        IVA = (precio * 21) / 100;
        
        precioFinal = precio + IVA;
        System.out.println("Su precio final es: " + precioFinal);
        
        
    }

}
