/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_var_1;

import java.util.Scanner;

public class App {
   

    //EJERCICIO 1
    
    public static void main(String[] args) {
        //String lineaDeTeclado;
        int x;
        int y;
        int suma;
        int resta;
        int multiplicacion;
        double division;
        
        x = 200;
        y = 111;
        suma = x + y;
        resta = x - y;
        division = x / y;
        multiplicacion = x * y;
        
        System.out.println("x vale " + x);
        System.out.println("y vale " + y);
        
        System.out.println("su suma es " + suma);
        System.out.println("su resta es " + resta);
        System.out.println("su multiplicacion es " + multiplicacion);
        System.out.println("su division es " + division);
        
        //EJERCICIO 2
 
        
        //lineaDeTeclado = miScan.nextLine();
        //System.out.println("Esto sale en el terminal " + lineaDeTeclado);
        
       
    }
}
