/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ECB4;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        int Par;
        int Impar;

        Scanner teclado = new Scanner(System.in);

        System.out.println("Introduzca un número par:");
        Par = teclado.nextInt();

        if (Par % 2 != 0) {
            System.out.println("El número no es par.");
        }
        System.out.println("Introduzca un número impar:");
        Impar = teclado.nextInt();
        if (Impar % 2 == 0) {
            System.out.println("El número no es impar.");
        }
        if (Impar % 2 == 0 || Par % 2 != 0){
            System.out.println("Reinicie el programa para volver a intentarlo.");
        }
}
}
