/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ECB3;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

    int Par;
    int Impar;
    
    Scanner teclado = new Scanner(System.in);
    
    System.out.print("Ingrese el numero par:");
    Par = teclado.nextInt();
     if (Par % 2 == 0){
         System.out.print("El numero es par, ingrese un número impar:");
         Impar = teclado.nextInt();
         if (Impar % 2 == 0){
             System.out.print("El numero es incorrecto, inicie el programa de nuevo para reintentarlo.");
         }else System.out.print("Ambos numeros son correctos!");
         
         
     }else System.out.print("No es correcto, inicie el programa de nuevo para reintentarlo.");
         
    
    
}
}