/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_bucles_2;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);
        System.out.println("Ingrese el número:");
        int numero = teclado.nextInt();
        int multiplo = 1;
        
    while (multiplo <=10){
	System.out.println(numero * multiplo);
        multiplo++; }
    }
}
