/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_bucles_3;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner teclado = new Scanner(System.in);
        System.out.println("Añada número:");
        int numero = teclado.nextInt();
        int multiplo = 1;
    //almenos una vez debe ejecutarse    
    do{ 
	System.out.println(numero * multiplo);
        multiplo++; 
    } while(multiplo<=10);
    
    }
}
