/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_var_1;

import java.util.Scanner;


public class App {
   

  
    
    public static void main(String[] args) {

        Scanner teclado = new Scanner(System.in);
        //se cambia la x por un número en el ejercicio 1, en el dos hacemos lo siguiente:
        System.out.println("Ingrese valor de X");
        int x = teclado.nextInt();
        System.out.println("x vale " + x);
        
        System.out.println("Ingrese valor de Y");
        int y = teclado.nextInt();
        System.out.println("y vale " + y);
        int suma;
        int resta;
        int multiplicacion;
        float division;
       
        suma = x + y;
        resta = x - y;
        division = x / y;
        multiplicacion = x * y;
        
      
        
        
        System.out.println("su suma es " + suma);
        System.out.println("su resta es " + resta);
        System.out.println("su multiplicacion es " + multiplicacion);
        System.out.println("su division es " + division);
        
       
    }
}
