/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ECB5;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        Scanner teclado = new Scanner(System.in);
        int numero;
        int suma = 0;
        int i;
        
        System.out.println("Elija un número para ver la suma de sus anteriores.");
        numero = teclado.nextInt();
        
       for(i=1; i<=numero;i++){
           
           suma = suma + i;
       }
        System.out.println(suma);
        

}
}
