/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_bucles_1;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        int numero;
        int multiplo;

        Scanner teclado = new Scanner(System.in);
        System.out.println("Inserte un nuevo número:");
        numero = teclado.nextInt();

        for (multiplo = 1; multiplo <= 10; multiplo++) {
            System.out.println(numero * multiplo);
        }
    }
}
