/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_bucles_4;



public class App {
    public static void main(String[] args) {
        
  
        int cAtras; 
        
        
        for (cAtras = 21; cAtras >=1 ;cAtras--){
            System.out.println( cAtras - 1);
        }
        
    }
}
