/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.cajaFuerteMAin;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner teclado = new Scanner(System.in); //teclado = objeto
        //clase       objeto
        CajaFuerte miCajaCaudales;

        miCajaCaudales = new CajaFuerte();

        int select;
        String oldPassword;
        String newPassword;
        String Password;

        do {
            System.out.println("1. Asignar nueva combinación");
            System.out.println("2. Abrir caja fuerte");
            System.out.println("0. Salir");

            select = teclado.nextInt();
            if (select == 1) {
                System.out.println("Introduzca antigua contraseña:");
                oldPassword = teclado.next();
                System.out.println("Introduzca nueva contraseña:");
                newPassword = teclado.next();
                if (miCajaCaudales.changePassword(oldPassword, newPassword)) {
                    System.out.println("Contraseña actualizada");
                } else 
                {
                    System.out.println("La contraseña antigua no era correcta");
                }

            } else if (select == 2) {
                System.out.println("Introduzca contraseña:");
                Password = teclado.next();

                if (miCajaCaudales.open(Password)) {
                    System.out.println("Contraseña correcta, caja abierta");
                } else {
                    System.out.println("Contraseña incorrecta");
                }

            } else if (select != 0) {
                System.out.println("\nNo existe esa opción");
                System.out.println("");

            }
        } while (select != 0);
    }
}
//##########################################################################
