/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ECB2;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

    int Par;
    int Impar;
    
    Scanner teclado = new Scanner(System.in);
    
    System.out.print("Ingrese el numero par:");
    Par = teclado.nextInt();
    
    System.out.print("Ingrese el número impar:");
    Impar = teclado.nextInt();
    
     if (Par % 2 == 0 && Impar % 2 != 0) {
            System.out.println("Los numeros son correctos");
        } else {
            System.out.println("Los numeros no son correctos");
        }
    
    
}
}
