/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_if_2;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.print("Introduzca día de la semanxa en número (1-7)");
        Scanner teclado = new Scanner(System.in);

        int diaSemana;

        diaSemana = teclado.nextInt();

        if (diaSemana == 1) {
            System.out.println("Es Lunes");
        }
        if (diaSemana == 2) {
            System.out.println("Es Martes");
        }
        if (diaSemana == 3) {
            System.out.println("Es Miercoles");
        }
        if (diaSemana == 4) {
            System.out.println("Es Jueves");
        }
        if (diaSemana == 5) {
            System.out.println("Es Viernes");
        }
        if (diaSemana == 6) {
            System.out.println("Es Sabado");
        }
        if (diaSemana == 7) {
            System.out.println("Es Domingo");
        }
        
    }

}
